# Generated by Django 4.2.7 on 2023-11-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnh',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
