# Generated by Django 4.2.7 on 2023-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_cliente_cnh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=255)),
                ('portas', models.IntegerField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=8)),
                ('placa', models.CharField(max_length=7)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
    ]
