# Generated by Django 4.2.7 on 2023-11-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locadora.cliente')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locadora.carro')),
            ],
        ),
    ]
